"""
Master Urls
"""
# pylint: disable=E0401
from django.urls import path
from masters.views import customers,products, product_type, category, drone_type, log_fields_template, settings, country, state,purpose, reason

urlpatterns = [
     path('customers/', customers.MasterCustomers.as_view(),
          name='Manage customers'),
     path('customers/add/', customers.MasterCustomersAdd.as_view(),
          name='Manage customers Add'),
     path('customers_admin/<str:cid>/', customers.MasterCustomersSave.as_view(),
          name='Manage customers Save'),
     path('customers/edit/<int:cid>/', customers.MasterCustomersEdit.as_view(),
          name='Manage customers Edit'),
     path('customers/get_state/', customers.GetState.as_view(),
          name='Get State'),
     path('customers_user/', customers.MasterCustomersUserSave.as_view(),
          name='Manage customers User Save'),
     path('success/', customers.SuccessPage.as_view(),
          name='Success Page'),
     path('verify_email/<str:cid>/<str:t>/', customers.EmailVarificaion.as_view(),
          name='Success Page 1'),
     path('save_new_password/', customers.SaveNewPassword.as_view(),
          name='Save New Password'),
     path('reset_password/<str:cid>/<str:t>/', customers.ResetPassword.as_view(),
          name='Reset Password'),
     path('pass-success/', customers.PassSuccessPage.as_view(),
          name='Password Success Page'),
     path('products/', products.Products.as_view(),
          name='product Page List'),
     path('products/add/', products.ProductAdd.as_view(),
          name='product Page Add'),
     path('products/edit/<int:cid>/', products.ProductEdit.as_view(),
          name='Product Edit'),
     path('products/get_data/', products.GetData.as_view(),
          name='Edt Product Edit data'),
     path('products/get_data_cb/', products.GetDataCB.as_view(),
          name='get_data_cb'),

     path('products/update/', products.ProductUpdate.as_view(),
          name='Product Update'),
     path('product_type/', product_type.ProductTypeList.as_view(),
          name='product Type List'),
     path('product_type/add/', product_type.ProductTypeAdd.as_view(),
          name='product Type Add'),
     path('product_type/update/', product_type.ProductTypeUpdate.as_view(),
          name='product Type Update'),
     path('category/', category.CategoryList.as_view(),
          name='category List'),
     path('category/add/', category.CategoryAdd.as_view(),
          name='category Add'),
     path('category/update/', category.CategoryUpdate.as_view(),
          name='category Update'),
     path('log_field_template/list/', log_fields_template.TemplateList.as_view(),
          name='Template List'),
     path('log_field_template/add/', log_fields_template.TemplateAdd.as_view(),
          name='Template Add'),
     path('log_field_template/get_fields/', log_fields_template.GetFields.as_view(),
          name='Get Fields'),
     path('log_field_template/save_fields/', log_fields_template.SaveFields.as_view(),
          name='Save Fields'),
     path('log_field_template/edit/<int:cid>/', log_fields_template.EditFields.as_view(),
          name='Field Type Edit'),
     path('log_field_template/get_data/', log_fields_template.GetData.as_view(),
          name='Field Edit data'),
     path('log_field_template/update_fields/', log_fields_template.UpdateFields.as_view(),
          name='Field Update data'),
     path('products/activate/', products.ActivateDrone.as_view(),
          name='Activate products'),
     path('country/', country.CountryList.as_view(),
          name='Countrylist'),
     path('country/add/', country.CountryAdd.as_view(),
          name='SaveCountry'),
     path('country/update/', country.CountryUpdate.as_view(),
          name='UpdateCountry'),
     path('settings/', settings.SettingsList.as_view(),
          name='Settings List'),
     path('settings/add/', settings.SettingsAdd.as_view(),
          name='Settings Add'),
     path('settings/update/', settings.SettingsUpate.as_view(),
          name='Settings Update'),
     path('state/', state.StateList.as_view(),
          name='Statelist'),
     path('state/add/', state.StateAdd.as_view(),
          name='SaveState'),
     path('state/update/', state.StateUpdate.as_view(),
          name='UpdateState'),
     path('purpose/', purpose.PurposeList.as_view(),
          name='Purpose list'),
     path('purpose/add/', purpose.PurposeAdd.as_view(),
          name='Save Purpose'),
     path('purpose/update/', purpose.PurposeUpdate.as_view(),
          name='Update Purpose'),
     path('drone_type/', drone_type.DroneTypeList.as_view(),
          name='Drone Type list'),
     path('drone_type/add/', drone_type.DroneTypeAdd.as_view(),
          name='Save Drone Type'),
     path('drone_type/update/', drone_type.DroneTypeUpdate.as_view(),
          name='Drone Type Purpose'),
     path('reason/', reason.ReasonList.as_view(),
          name='reason List'),
     path('reason/add/', reason.ReasonAdd.as_view(),
          name='reason Add'),
     path('reason/update/', reason.ReasonUpdate.as_view(),
          name='reason Update'),

     path('customers/get_drone_list/', customers.GetDroneList.as_view(),
          name='GetDroneList'),

]
