# Generated by Django 4.0.2 on 2022-02-28 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drone_management', '0003_sensormaster_rcmaster_cameramaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('uin', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
                ('video_link', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True, null=True)),
                ('additional_features', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.batterymaster')),
                ('camera', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.cameramaster')),
                ('created_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drone_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.dronetype')),
                ('remote_control', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.rcmaster')),
                ('sensors', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.sensormaster')),
            ],
            options={
                'db_table': 'dms_drones',
            },
        ),
        migrations.CreateModel(
            name='DroneComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.batterymaster')),
                ('camera', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.cameramaster')),
                ('created_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.drone')),
                ('sensors', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.sensormaster')),
            ],
            options={
                'db_table': 'dms_drone_components',
            },
        ),
    ]
