# Generated by Django 4.0.2 on 2022-02-28 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0004_drone_dronecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.ImageField(upload_to='drone_images'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='video_link',
            field=models.FileField(null=True, upload_to='drone_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
