# Generated by Django 4.0.2 on 2022-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0007_remove_drone_battery_remove_drone_camera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='remote_control',
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='fc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='frame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='qgc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dronecomponent',
            name='rc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='battery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='camera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dronecomponent',
            name='sensors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
