# Generated by Django 4.0.2 on 2022-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0008_remove_drone_remote_control_dronecomponent_fc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronetype',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='drone_type_images/'),
        ),
        migrations.AddField(
            model_name='dronetype',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='drone_type_images/'),
        ),
        migrations.AddField(
            model_name='dronetype',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
