# Generated by Django 4.0.2 on 2022-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0009_dronetype_image1_dronetype_image2_dronetype_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dronetype',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='schema',
        ),
        migrations.AddField(
            model_name='drone',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='drone_type_images/'),
        ),
        migrations.AddField(
            model_name='drone',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='drone_type_images/'),
        ),
        migrations.AddField(
            model_name='drone',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
