# Generated by Django 4.0.2 on 2022-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0010_remove_dronetype_image1_remove_dronetype_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='allocated',
            field=models.BooleanField(default=True),
        ),
    ]
