# Generated by Django 4.0.2 on 2022-06-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0011_drone_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
