# Generated by Django 4.0.2 on 2022-06-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0012_alter_drone_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dms_drone_status',
            },
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.dronestatus'),
        ),
    ]
