# Generated by Django 4.0.2 on 2022-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0013_dronestatus_drone_drone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronestatus',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
