# Generated by Django 4.0.2 on 2022-06-26 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drone_management', '0014_dronestatus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DronePurpose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dms_drone_purpose',
            },
        ),
        migrations.AddField(
            model_name='dronetype',
            name='purpose',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.dronepurpose'),
        ),
    ]
