# Generated by Django 4.0.2 on 2022-06-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0015_dronepurpose_dronetype_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='drone_purpose',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.dronepurpose'),
        ),
    ]
