# Generated by Django 4.0.2 on 2022-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0016_drone_drone_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronetype',
            name='additional_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
