# Generated by Django 4.0.2 on 2022-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0021_alter_dronestatus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='uin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
