# Generated by Django 4.0.2 on 2022-02-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.country'),
        ),
    ]
