# Generated by Django 4.0.2 on 2022-02-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_customer_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='', max_length=80)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('mission_commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customer')),
            ],
            options={
                'db_table': 'dms_project',
            },
        ),
    ]
