# Generated by Django 4.0.2 on 2022-03-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_project'),
        ('masters', '0008_delete_dmssetting'),
    ]

    operations = [
    ]
