# Generated by Django 4.0.2 on 2022-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_merge_0007_project_0008_delete_dmssetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conf_key', models.TextField()),
                ('conf_value', models.TextField()),
                ('conf_description', models.TextField()),
            ],
            options={
                'db_table': 'dms_settings',
            },
        ),
    ]
