# Generated by Django 4.0.2 on 2022-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_dmssetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('pilot_license', models.TextField()),
                ('expiry_date', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('parent_id', models.CharField(default='', max_length=80)),
            ],
            options={
                'db_table': 'dms_pilot',
            },
        ),
    ]
