# Generated by Django 4.0.2 on 2022-03-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='pilot_license',
            field=models.FileField(upload_to='license_uploads/'),
        ),
    ]
