# Generated by Django 4.0.2 on 2022-03-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_project_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilot',
            old_name='parent_id',
            new_name='customer_id',
        ),
    ]
