# Generated by Django 4.0.2 on 2022-03-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_rename_parent_id_pilot_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='parent_id',
        ),
    ]
