# Generated by Django 4.0.2 on 2022-03-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_remove_customer_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(default='', max_length=80)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('customer_id', models.CharField(default='', max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.pilot')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.project')),
            ],
            options={
                'db_table': 'dms_plan',
            },
        ),
    ]
