# Generated by Django 4.0.2 on 2022-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_alter_customer_user_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='pilot',
            field=models.BooleanField(default=False),
        ),
    ]
