# Generated by Django 4.0.2 on 2022-03-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_alter_project_mission_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customeruser'),
        ),
    ]
