# Generated by Django 4.0.2 on 2022-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_alter_plan_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
