# Generated by Django 4.0.2 on 2022-03-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0007_remove_drone_battery_remove_drone_camera_and_more'),
        ('masters', '0023_plan_end_time_plan_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='end_date',
            new_name='plan_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_date',
        ),
        migrations.CreateModel(
            name='DroneAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customeruser')),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.drone')),
            ],
            options={
                'db_table': 'dms_drone_allocation',
            },
        ),
    ]
