# Generated by Django 4.0.2 on 2022-03-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_rename_end_date_plan_plan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customer'),
        ),
        migrations.AlterField(
            model_name='droneallocation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customer'),
        ),
    ]
