# Generated by Django 4.0.2 on 2022-03-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0007_remove_drone_battery_remove_drone_camera_and_more'),
        ('masters', '0025_remove_plan_customer_id_remove_project_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.drone'),
        ),
    ]
