# Generated by Django 4.0.2 on 2022-03-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_plan_drone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='account_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
