# Generated by Django 4.0.2 on 2022-03-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_checklisttype_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='description',
            new_name='schema',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='type',
        ),
        migrations.AddField(
            model_name='checklist',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.plan'),
        ),
        migrations.DeleteModel(
            name='ChecklistType',
        ),
    ]
