# Generated by Django 4.0.2 on 2022-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_rename_description_checklist_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checked',
        ),
        migrations.AddField(
            model_name='checklist',
            name='type',
            field=models.CharField(default='', max_length=80),
        ),
    ]
