# Generated by Django 4.0.2 on 2022-04-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_remove_checklist_checked_checklist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_file', models.FileField(blank=True, null=True, upload_to='plan_logs/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.plan')),
            ],
            options={
                'db_table': 'dms_plan_logs',
            },
        ),
    ]
