# Generated by Django 4.0.2 on 2022-04-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_planlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('air_speed', models.TextField()),
                ('flight_time', models.TextField()),
                ('altitude_relative', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.planlog')),
            ],
            options={
                'db_table': 'dms_plan_reports',
            },
        ),
    ]
