# Generated by Django 4.0.2 on 2022-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_planreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='planreport',
            name='battery_consumed',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='planreport',
            name='distance_to_gcs',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='planreport',
            name='flight_distance',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='planreport',
            name='flight_time',
            field=models.CharField(default='', max_length=80),
        ),
    ]
