# Generated by Django 4.0.2 on 2022-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_planreport_battery_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planreport',
            name='flight_time_max',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='planreport',
            name='flight_time',
            field=models.TextField(),
        ),
    ]
