# Generated by Django 4.0.2 on 2022-04-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_planreport_flight_time_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planreport',
            old_name='battery_consumed',
            new_name='battery_consumed_max',
        ),
        migrations.RenameField(
            model_name='planreport',
            old_name='distance_to_gcs',
            new_name='distance_to_gcs_max',
        ),
        migrations.RenameField(
            model_name='planreport',
            old_name='flight_distance',
            new_name='flight_distance_max',
        ),
    ]
