# Generated by Django 4.0.2 on 2022-04-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0007_remove_drone_battery_remove_drone_camera_and_more'),
        ('masters', '0036_rename_battery_consumed_planreport_battery_consumed_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.CharField(default='', max_length=80)),
                ('flying_time', models.CharField(default='', max_length=80)),
                ('plans', models.CharField(default='', max_length=80)),
                ('gc_con_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.drone')),
            ],
            options={
                'db_table': 'dms_dashboard_datas',
            },
        ),
    ]
