# Generated by Django 4.0.2 on 2022-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0038_dashboarddata_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='plan_files/'),
        ),
    ]
