# Generated by Django 4.0.2 on 2022-04-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0040_category_producttype_transactionlog_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_feature',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='warranty_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
