# Generated by Django 4.0.2 on 2022-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0042_alter_product_trans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trans_type',
            field=models.CharField(choices=[('new', 'new'), ('allocated', 'allocated'), ('Danaged', 'Danaged')], default='new', max_length=10),
        ),
    ]
