# Generated by Django 4.0.2 on 2022-06-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0044_customeruser_pilot_license_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='additional_fields',
            field=models.TextField(default='', null=True),
        ),
    ]
