# Generated by Django 4.0.2 on 2022-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0046_alter_product_trans_type_alter_producttype_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(default='', max_length=80)),
                ('log_fields', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dms_log_template',
            },
        ),
    ]
