# Generated by Django 4.0.2 on 2022-06-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0014_dronestatus_type'),
        ('masters', '0047_logtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drone_status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.dronestatus'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
