# Generated by Django 4.0.2 on 2022-06-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0016_drone_drone_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0049_product_active_product_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneConfiguraion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_id', models.CharField(default='', max_length=80, null=True)),
                ('fc_id', models.CharField(default='', max_length=80, null=True)),
                ('host', models.CharField(default='', max_length=80, null=True)),
                ('port', models.CharField(default='', max_length=80, null=True)),
                ('username', models.CharField(default='', max_length=80, null=True)),
                ('password', models.CharField(default='', max_length=80, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.drone')),
                ('template', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.logtemplate')),
            ],
            options={
                'db_table': 'dms_drone_configuraion',
            },
        ),
    ]
