# Generated by Django 4.0.2 on 2022-06-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0050_droneconfiguraion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='error_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
