# Generated by Django 4.0.2 on 2022-07-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_management', '0016_drone_drone_purpose'),
        ('masters', '0051_dashboarddata_error_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_usage', models.CharField(default='', max_length=80, null=True)),
                ('vertual_memory', models.CharField(default='', max_length=80, null=True)),
                ('swap_memory', models.CharField(default='', max_length=80, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_management.drone')),
            ],
            options={
                'db_table': 'dms_consumption_log',
            },
        ),
    ]
