# Generated by Django 4.0.2 on 2022-07-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0052_consumptionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptionlog',
            old_name='vertual_memory',
            new_name='virtual_memory',
        ),
    ]
