# Generated by Django 4.0.2 on 2022-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0055_rename_con_date_consumptionlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionlog',
            name='cpu_usage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionlog',
            name='swap_memory',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionlog',
            name='virtual_memory',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
