# Generated by Django 4.0.2 on 2022-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0059_alter_country_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsBuildLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('build_no', models.CharField(default='', max_length=80)),
                ('build_date', models.DateTimeField(auto_now_add=True)),
                ('portal', models.CharField(default='', max_length=80)),
            ],
            options={
                'db_table': 'dms_build_log',
            },
        ),
    ]
