# Generated by Django 4.0.2 on 2022-09-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0060_dmsbuildlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
