# Generated by Django 4.0.2 on 2022-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0061_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='dmssetting',
            name='conf_key',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='logtemplate',
            name='template_name',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
    ]
