# Generated by Django 4.0.2 on 2022-09-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0062_alter_category_model_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
    ]
