# Generated by Django 4.0.2 on 2022-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0063_alter_state_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(error_messages={'name': 'This email has already been registered.'}, max_length=40, unique=True),
        ),
    ]
