# Generated by Django 4.0.2 on 2022-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0067_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(blank=True, choices=[('Battery', 'Battery'), ('Sensor', 'Sensor'), ('Camera', 'Camera'), ('RC', 'RC')], default='Battery', max_length=80, null=True),
        ),
    ]
