# Generated by Django 4.0.2 on 2022-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0068_alter_producttype_name_alter_producttype_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='dmssetting',
            name='conf_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logtemplate',
            name='template_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
