"""
Django settings for dms project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging.config
import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u0uqziwz^%nys())1iwe$!8%i7n_&42e3hch*cu$sq09!o!!9%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'login',
    'dashboard',
    'userpermissions',
    'api',
    'masters',
    'corsheaders',
	'users',
    'drone_management'
]


REST_FRAMEWORK = {
    # 'DEFAULT_PARSER_CLASSES': (
    #     'rest_framework_xml.parsers.XMLParser',
    # ),
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'api.renderers.CustomRenderer',
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    }
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
	'dms.middleware.SelectorMiddleware',

	
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
ROOT_URLCONF = 'dms.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')), (os.path.join(BASE_DIR, 'dashboard/templates')), (os.path.join(BASE_DIR, 'login/templates')), (os.path.join(BASE_DIR, 'masters/templates')), (os.path.join(BASE_DIR, 'drone_management/templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dms.wsgi.application'

file_name = datetime.datetime.now().strftime("%Y-%m-%d")
LOGGING_CONFIG = None
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'remove_debug': {
            '()': 'userpermissions.log_filter.AwesomeFilter'
        },
    },
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(message)s %(levelname)s [%(name)s.%(funcName)s:%(lineno)d]',
        },
    },
    'handlers': {
        'default': {
            'level': 'DEBUG',
            'filters': ['remove_debug'],
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/'+str(file_name)+'.log'),
            # 'maxBytes': 1024*1024*5,  # 5 MB
            # 'backupCount': 5,
            'when': 'midnight',
            'formatter': 'standard',
        },
    },
    'loggers': {
        '': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
})

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dms_2022',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# AES256 key & IV
KEY = 'A1A2A3A4A5A6A7A8A9A1A2A3A4A5CAFE'
IV = 'A1A2A3A4A5A6A7A8'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_URL = '/static/'

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dms/masters/customers/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# MEDIA_URL = '/docs/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'documents')

APP_NAME = 'AVM'
MEDIA_ROOT = os.path.join(BASE_DIR, 'attachments')
MEDIA_URL = '/attachments/'
LOG_ROOT = os.path.join(BASE_DIR, 'log')
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_USE_TLS = True

# Base URL of the Application 
BASE_URL = 'http://127.0.0.1:8000'
DMS_URL = 'http://localhost:4200'

TOKEN_EXPIRED_AFTER_SECONDS = 3600
EMAIL_EXPIRED_AFTER_HOUR = 1

WARRANTY_LIMIT = 12 #months
PURCHASE_LIMIT = 90 #days
TABLE_ROW_LIMIT = 10