# Generated by Django 2.2 on 2020-11-26 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uje_group',
            },
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uje_permission',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uje_roles',
            },
        ),
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(db_column='role_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='userpermissions.RoleModel')),
                ('user_id', models.ForeignKey(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uje_user_roles',
            },
        ),
        migrations.CreateModel(
            name='RoleGroupModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(db_column='group_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='userpermissions.GroupModel')),
                ('role_id', models.ForeignKey(db_column='role_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='userpermissions.RoleModel')),
            ],
            options={
                'db_table': 'uje_role_group',
            },
        ),
        migrations.CreateModel(
            name='GroupPermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(db_column='group_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='userpermissions.GroupModel')),
                ('permission_id', models.ForeignKey(db_column='permission_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='userpermissions.PermissionModel')),
            ],
            options={
                'db_table': 'uje_group_permission',
            },
        ),
    ]
