# Generated by Django 2.2 on 2020-11-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpermissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupmodel',
            table='serviceapp_group',
        ),
        migrations.AlterModelTable(
            name='grouppermissionmodel',
            table='serviceapp_group_permission',
        ),
        migrations.AlterModelTable(
            name='permissionmodel',
            table='serviceapp_permission',
        ),
        migrations.AlterModelTable(
            name='rolegroupmodel',
            table='serviceapp_role_group',
        ),
        migrations.AlterModelTable(
            name='rolemodel',
            table='serviceapp_roles',
        ),
        migrations.AlterModelTable(
            name='userrolemodel',
            table='serviceapp_user_roles',
        ),
    ]
