# Generated by Django 4.0.2 on 2022-02-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpermissions', '0003_alter_groupmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrolemodel',
            table='dms_user_roles',
        ),
    ]
